#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 16 22:06:03 2019

@author: simerjotkaur
"""

sents = [[['M','y'],['n','a','m','e'],['i','s'],['A','m','a','n']],
        [['M','y'],['n','a','m','e'],['i','s'],['S','i','m','e','r'],['K','a','u','r']]]
char_pad_token = 'c'
max_word_length = 5
sents_padded = []
max_len = max(len(s) for s in sents)
for s in sents:
    s_padded = [[char_pad_token] * max_word_length] * max_len
    s_padded[:len(s)] = s
    words_padded = []
    for w in s_padded:
        if len(w)<=max_word_length:
            padded = [char_pad_token] * max_word_length
            padded[:len(w)] = w
        else:
            padded = w[:max_word_length]
        words_padded.append(padded)
    sents_padded.append(words_padded)
print(sents_padded)